HW_20211103/Lab_HW/Models/Bike.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_HW.Models
{
    public class Bike
    {
        public int Id { get; set; }
        public string Lv { get; set; }
        public int cc { get; set; }
    }
}

HW_20211103/Lab_HW/Models/ErrorViewModel.cs
using System;

namespace Lab_HW.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HW_20211103/Lab_HW/Controllers/BikeController.cs
using Lab_HW.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_HW.Controllers
{
    public class BikeController : Controller
    {

        static List<Bike> bikes = new List<Bike>()
        {
            new Bike{ Id = 1,Lv = "白牌",cc = 150},
            new Bike{ Id = 2,Lv = "黃牌",cc = 350},
            new Bike{ Id = 3,Lv = "紅牌",cc = 650}
        };


        // GET: BikeController
        public ActionResult Index()
        {
            return View(bikes);
        }

        [HttpPost]
        public ActionResult Index(string id, string lv, string cc)
        {
            List<Bike> Data = new List<Bike>();

            if (id != null)
            {
                Data = bikes.Where(x => x.Id == int.Parse(id)).ToList();
            }
            else if (lv != null)
            {
                Data = bikes.Where(x => x.Lv == lv).ToList();
            }
            else if (cc != null)
            {
                Data = bikes.Where(x => x.cc == int.Parse(cc)).ToList();
            }

            return View(Data);
        }

        // GET: BikeController/Details/5
        public ActionResult Details(int id)
        {
            Bike data = bikes.FirstOrDefault(x => x.Id == id);

            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // GET: BikeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BikeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bike collection)
        {
            try
            {
                bikes.Add(collection);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BikeController/Edit/5
        public ActionResult Edit(int id)
        {
            Bike data = bikes.FirstOrDefault(x => x.Id == id);

            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // POST: BikeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Bike collection)
        {
            try
            {
                Bike data = bikes.FirstOrDefault(x => x.Id == id);

                if (data == null)
                {
                    return NotFound();
                }

                data.Lv = collection.Lv;
                data.cc = collection.cc;

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BikeController/Delete/5
        public ActionResult Delete(int id)
        {
            Bike data = bikes.FirstOrDefault(x => x.Id == id);

            if (data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // POST: BikeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[ActionName("Delete")]
        public ActionResult Delete(Bike collection)
        {
            try
            {
                Bike data = bikes.FirstOrDefault(x => x.Id == collection.Id);

                bikes.Remove(data);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HW_20211103/Lab_HW/Controllers/HomeController.cs
using Lab_HW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_HW.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HW_20211103/Lab_HW/Views/Bike/Create.cshtml
@model Lab_HW.Models.Bike

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Bike</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lv" class="control-label"></label>
                <input asp-for="Lv" class="form-control" />
                <span asp-validation-for="Lv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cc" class="control-label"></label>
                <input asp-for="cc" class="form-control" />
                <span asp-validation-for="cc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HW_20211103/Lab_HW/Views/Bike/Delete.cshtml
@model Lab_HW.Models.Bike

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bike</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cc)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HW_20211103/Lab_HW/Views/Bike/Details.cshtml
@model Lab_HW.Models.Bike

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Bike</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cc)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

HW_20211103/Lab_HW/Views/Bike/Edit.cshtml
@model Lab_HW.Models.Bike

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Bike</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lv" class="control-label"></label>
                <input asp-for="Lv" class="form-control" />
                <span asp-validation-for="Lv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cc" class="control-label"></label>
                <input asp-for="cc" class="form-control" />
                <span asp-validation-for="cc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HW_20211103/Lab_HW/Views/Bike/Index.cshtml
@model IEnumerable<Lab_HW.Models.Bike>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                <form action="/Bike/Index" method="post">
                    <input name="id" placeholder="Id" />
                    <button type="submit">搜尋</button>
                </form>
            </th>
            <th>
                <form action="/Bike/Index" method="post">
                    <input name="lv" placeholder="Lv" />
                    <button type="submit">搜尋</button>
                </form>
            </th>
            <th>
                <form action="/Bike/Index" method="post">
                    <input name="cc" placeholder="cc" />
                    <button type="submit">搜尋</button>
                </form>
            </th>
        </tr>
    </thead>
</table>


<hr>
<p>
    <a asp-action="Create">Create New</a>
</p>

<p>
    <a asp-action="Index">Reset</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cc)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cc)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

HW_20211103/Lab_HW/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HW_20211103/Lab_HW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab_HW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab_HW</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bike" asp-action="Index">Bike</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; 2021 - Lab_HW - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>